data-path="/home/vanir/ehr-blockchain/blockchain/data/hospital4-validator"
genesis-file="/home/vanir/ehr-blockchain/blockchain/genesis/qbft-genesis.json"
node-private-key-file="/home/vanir/ehr-blockchain/blockchain/keys/hospital4-validator/key"
rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT","ADMIN","WEB3"]
rpc-http-cors-origins=["*"]
rpc-http-host="0.0.0.0"
rpc-http-port=8548
host-allowlist=["*"]
min-gas-price=0
p2p-port=30306
bootnodes=["enode://0x72ea352d90efe0f44826c6cd0b7713b7f7b8848cc8bff0c8032f27c103d796dd7429004e3eb533a0138b66d7798ff487e5e9f95b3553ac5ece7ea03cf25707f5@127.0.0.1:30303"]
