data-path="/home/vanir/ehr-blockchain/blockchain/data/hospital3-validator"
genesis-file="/home/vanir/ehr-blockchain/blockchain/genesis/qbft-genesis-4nodes.json"
node-private-key-file="/home/vanir/ehr-blockchain/blockchain/keys/hospital3-validator/key"
rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT","ADMIN","WEB3"]
rpc-http-cors-origins=["*"]
rpc-http-host="0.0.0.0"
rpc-http-port=8547
host-allowlist=["*"]
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/home/vanir/ehr-blockchain/blockchain/permissions/nodes.toml"
min-gas-price=0
p2p-port=30305
p2p-host="0.0.0.0"
bootnodes=["enode://0x3cc8b092a48ef3c2aa72418f9152958a4f48f35e040154966ea579875d2193267df3ca25b9833e3ac43e537c4b0645f673608f2877ad392776d1c80b3a084916@127.0.0.1:30303"]
