data-path="/home/vanir/ehr-blockchain/blockchain/data/hospital2"
genesis-file="/home/vanir/ehr-blockchain/blockchain/genesis/qbft-genesis.json"
node-private-key-file="/home/vanir/ehr-blockchain/blockchain/keys/hospital2/key"
rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT","ADMIN","WEB3"]
rpc-http-cors-origins=["*"]
rpc-http-host="0.0.0.0"
rpc-http-port=8546
host-allowlist=["*"]
min-gas-price=0
p2p-port=30304
p2p-host="0.0.0.0"
bootnodes=["enode://0x3cc8b092a48ef3c2aa72418f9152958a4f48f35e040154966ea579875d2193267df3ca25b9833e3ac43e537c4b0645f673608f2877ad392776d1c80b3a084916@127.0.0.1:30303"]
